# Project information
site_name: Jintaoxu's Page
site_url: https://taoger-xu.github.io/note/
site_author: Jintao Xu

# Repository
repo_name: note
repo_url: https://github.com/Taoger-Xu/note

theme:
  name: material
  font:
    text: LXGW WenKai Screen  
    code: Monaspace Krypton

  favicon: icons/cat.svg
  icon:
    repo: fontawesome/brands/github-alt # the github cat icon in the topright
    logo: material/cat # the cat icon in the topleft
  features:
    # - navigation.prune
    - navigation.tracking
    - navigation.instant # optimize loading
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.action.edit # enable the button to edit the source code of the page
    - content.action.view # enable the button to view the source code of the page
    - content.code.copy # enable the button to copy the code block
    - search.suggest # auto suggestion
    - search.highlight # highlight when search
    - search.share # enable share when search
    - toc.follow # the sidebar will scroll automatically following the user
    
plugins:
  - search
  - meta-manager:
      merge_tags: true
  # - social: #social card
  #     enabled: !ENV [CI, false]
  #     cards: !ENV [CI, false]
  #     cards_font: Noto Sans SC
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [CI, false]
  - offline: # enable searching offline
      enabled: !ENV [OFFLINE, false]
  - glightbox
  - blog:
      post_url_format: "{slug}"
      blog_toc: true
      post_date_format: medium
      post_excerpt: required
      post_readtime_words_per_minute: 150
    
extra_css:
  - css/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
extra_javascript:
  - js/extra.js
  - js/tablesort.js
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # enable table sort
markdown_extensions:
  #enable admonition
  - admonition
  - pymdownx.details # enable ??? admonition
  - pymdownx.betterem # better emphasize
  - pymdownx.superfences: # allow nest codes
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format #enable code config


  - pymdownx.inlinehilite #inline code highlight
  - pymdownx.snippets #enable to embed arbitrary files
  - pymdownx.highlight:
      linenums: true # enable line display
      line_spans: __span
      pygments_lang_class: true # detect language automatically
      anchor_linenums: true # offer line anchor
  - pymdownx.keys # render key symbols
  - pymdownx.smartsymbols
  #enable button
  - attr_list
  #enable content tabs
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  #daigrams are not enabled
  - footnotes
  #enable emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator:
        !!python/name:material.extensions.emoji.to_svg #image alignment


  - md_in_html
  #better list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  #abbr
  - abbr
  #enable math syntax
  - pymdownx.arithmatex:
      generic: true
  #enable table of content
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  
nav:
  - Home:
      - index.md
  - Blog:
      - blog/index.md

  - Course:
      - course/index.md
      - CMU 15-213:
        - course/cmu15-213/index.md
        - Lab: course/cmu15-213/lab.md
        - Lec: course/cmu15-213/lec.md
      - cs61a:
        - course/cs61a/index.md
        - Lab: course/cs61a/lab.md
        - Project: course/cs61a/project.md
        - Lec: course/cs61a/lec.md
      - cs 106L:
        - course/cs106L/index.md
        - Lab: course/cs106L/lab.md
        - Lec: course/cs106L/lec.md
  - Paper:
      - paper/index.md